### ISSUE TITLE
Bugs on book build

### ISSUE THREAD

**Issue by ItsTheSky** [upperlevel/book-api#13]
Hello !
I already used your very giood API a couple of times for my plugnis, but one of user got that weird error on the build line:
![image](https://user-images.githubusercontent.com/50667548/105880182-57415580-6003-11eb-86ca-92b53a8a0d8f.png)

He's using paper 1.16.4, same as be, but I doesn't got that error at any times.
My class code can be found [here](https://paste.md-5.net/tolexopuwu.coffeescript) if you need it.
Thanks in advance ^^

**Comment by SnowyCoder** [comment]
Hello,  thanks for using the library! 
What version are you using?
This seems a lot like #9 and it should be fixed in version 1.4.

**Comment by ItsTheSky** [comment]
Hey
Oh yes, you've right, I was used 1.3 ^^'
I just upgraded to 1.4 and the error seems to be fixed, thanks you :)
