### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: org/bukkit/inventory/meta/BookMeta$Generation

### ISSUE THREAD

**Issue by JoaoGabrielCostaa** [upperlevel/book-api#14]
Hello, i'm using your API for books and i have this error in **git-PaperSpigot-0ed05fb8 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)** : 

https://pastebin.com/8abPS87X

Snippet of my code:
```java
//private code
```

```java
//MultipleAnimationRunnable.java
//private code
```

Grats, Atlas.

**Comment by SnowyCoder** [comment]
I tested the example plugin in PaperSpigot 1,8,8 (`git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)` downloaded from https://papermc.io/legacy) and every feature seems to work fine, can you provide a reproducible example?

**Comment by JoaoGabrielCostaa** [comment]
I'm using FlamePaper ([https://github.com/2LStudios-MC/FlamePaper](https://github.com/2LStudios-MC/FlamePaper))

**Comment by JoaoGabrielCostaa** [comment]
Full error here: https://pastebin.com/vtE39i9n

**Comment by JoaoGabrielCostaa** [comment]
Solved, my java obfuscator obfuscated your classes , sorry 

I solved by relocating with maven shaded

**Comment by SnowyCoder** [comment]
Ok, thanks for reporting it!
