### ISSUE TITLE
* Invalid Book Tag * when title is longer than 32 characters

### ISSUE THREAD

**Issue by ItsTheSky** [upperlevel/book-api#15]
Hello!
First, thanks of making that API, it was been very usefull!
However, from around a week, I always got that error:
![image](https://user-images.githubusercontent.com/50667548/107404299-70b7c680-6b06-11eb-9345-d20967719a24.png)
when I'm opening any book;
First I was thinking it was from me, but even your example of GitHub doesn't work :c
I'm on paper 1.16.4, and got Book-API as 1.4

**Comment by SnowyCoder** [comment]
Hello! Thanks for reporting this,
I have no idea on how to download paper spigot 1.16.4 but I tested the plugin example with paper spigot 1.16.5 and everything seems to work fine, can you give me more details?

**Comment by ItsTheSky** [comment]
Hey!
Yes of course!
After some search, my function seems weird;
With some of data, it work fine but with some od other it show that error.
I have been verify if every data are existing before opening the book, but can't found why it make mt that error :/
I've also debuging as much as I can, but dunno how can I debug the book's code since every of mine values seems fine ^^'

**Comment by SnowyCoder** [comment]
Mmmh, can you give me an example of code (and also of the data needed to run it) that shows that error?

**Comment by ItsTheSky** [comment]
Yep of course!
HEre's my function code:
https://paste.md-5.net/kugeresati.cs
and I registring all buildings on starting.
The buildings file is like that:
https://paste.md-5.net/ehuvekujob.bash
and that's what I normally got with a non-buggy book:
![image](https://user-images.githubusercontent.com/50667548/107424998-ad8fb780-6b1e-11eb-880a-57e6f88f15c2.png)
It does not work only for Gloryhall and Watchtower right now :/

**Comment by SnowyCoder** [comment]
I'm trying to understand your code but I don't have all of it (and it's quite long), could you try to build a minimal example of what does not work?

**Comment by ItsTheSky** [comment]
what do you mean by "minimal example" ?

**Comment by SnowyCoder** [comment]
Some code that does not depend on your plugin that I can run, I'm trying to run the code you gave me but I don't have `LangManager` or other parts of your code so I don't know what the BookApi gets as input

**Comment by ItsTheSky** [comment]
So I removed the code a little bit, so that you can try it out better !
Same error as before, even with only the name and the description showed
```java
	public void openBuildingsBook(Player player, Building b) {

		File playerFile = new File(SuperGuilds.getInstance().getDataFolder(), "players/" + player.getUniqueId() + ".yml");
		File buildingsFile = new File(SuperGuilds.getInstance().getDataFolder(), "buildings.yml");
		if (!playerFile.exists() || !buildingsFile.exists()) return;
		FileConfiguration playerConfig = YamlConfiguration.loadConfiguration(playerFile);
		File guildFile = new File(SuperGuilds.getInstance().getDataFolder(), "guilds/" + playerConfig.get("Data.Guild", "*") + ".yml");
		if (!guildFile.exists()) return;
		FileConfiguration guildConfig = YamlConfiguration.loadConfiguration(guildFile);

		BookUtil.PageBuilder page = new BookUtil.PageBuilder()
				.add(new TextComponent("&8&l»" + b.getName()))
				.newLine().newLine();

		page.add("§8§o" + b.getDescription()).newLine().newLine();


		ItemStack book = BookUtil.writtenBook()
				.author("Sky")
				.title("Buildings Information - " + b.getId())
				.pages(page.build())
				.build();

		Utils.openBook(player, book);
	}
```
EDIT : changed LangManager() to work with you

**Comment by SnowyCoder** [comment]
Seems like the problem is in the title: it should be only 32 characters or less ("Buildings Information - Gloryhall" is 33 chars).
Searching online I found that the maximum title length should be of 16 characters so I don't really know why it's working up to 32.
Anyways, I'll look more into this but I suggest you limit the title length

**Comment by ItsTheSky** [comment]
Okay thanks, i'll try it now

**Comment by ItsTheSky** [comment]
Oh yes, love you, it work well now 😂
Thanks again, maybe add warning if title is bigger than 16 character?

**Comment by SnowyCoder** [comment]
Yep, I think I'll throw an exception or something similar and add more documentation.
Thanks again! (I'll keep this issue open to track the changes)
