### ISSUE TITLE
Invalid Book tag when title is missing

### ISSUE THREAD

**Issue by ItsTheSky** [upperlevel/book-api#16]
Hey!
Yeah, it's me again xD
I got another InvalidBookTag error, just by using your example code from Github.
I have been verified the name in case it's longer than 32 chaeracter, but the error keep going :c
Here's my simle function : 
```java
	public Test(Player player) {

		ItemStack book = BookUtil.writtenBook()
			.author("Sky")
			.pages(
				new BaseComponent[]{
						new TextComponent("Test Book")
				},
				new BookUtil.PageBuilder()
						.add(new TextComponent("visit "))
						.add(
								BookUtil.TextBuilder.of("Spigot")
										.color(ChatColor.GOLD)
										.style(ChatColor.BOLD, ChatColor.ITALIC)
										.onClick(BookUtil.ClickAction.openUrl("https://www.spigotmc.org"))
										.onHover(BookUtil.HoverAction.showText("Open spigot!"))
										.build()
						)
						.add(" or ")
						.add(
								new ComponentBuilder("Bukkit")
										.color(net.md_5.bungee.api.ChatColor.BLUE)
										.bold(true)
										.italic(true)
										.event(new ClickEvent(ClickEvent.Action.OPEN_URL, "https://bukkit.org"))
										.event(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new BaseComponent[]{new TextComponent("Open bukkit!")}))
										.create()
						)
						.newLine()
						.add("I think that the ")
						.add(
								BookUtil.TextBuilder.of("TextBuilder")
										.color(ChatColor.AQUA)
										.style(ChatColor.BOLD)
										.onClick(BookUtil.ClickAction.changePage(3))
										.onHover(BookUtil.HoverAction.showText("TextBuilder's page"))
										.build()
						)
						.add(" is really useful to ")
						.add(
								BookUtil.TextBuilder.of("you")
										.color(ChatColor.AQUA)
										.style(ChatColor.BOLD)
										.onClick(BookUtil.ClickAction.runCommand("/kill"))//lol
										.onHover(BookUtil.HoverAction.showText("Kill yasself"))
										.build()
						)
						.build(),
				new BookUtil.PageBuilder()
						.add("TextBuilder's page")
						.newLine().newLine()
						.add("Isn't this amazing?")
						.build()
		).build();

		player.getInventory().addItem(book);
		BookUtil.openPlayer(player, book);
	}
```
N.B.: I also, as you can see, give the book to the player, but the same error appear when I open it :/
I'm using paper 1.16.4, with book-api 1.4.1

**Comment by SnowyCoder** [comment]
Thanks for the code, it's been a lot easier to debug with it.
Turns out you need to specify at least 3 things for a book to be valid: title, author and pages, if any one of them is missing the book won't be built correctly.
So the minimal code to build a book is:
```java
BookUtil.writtenBook()
    .title("")
    .author("")
    .pages()
    .build();
```
If any one of those is missing the NBT tag won't be present and the book will not display correctly.
I'm trying to build a check for that but I think it'll do more harm than good, in older version the "pages" list is not required (for example).
If you want to be sure that the book will always build correctly set all three of them (even to empty values).

**Comment by SnowyCoder** [comment]
An easy fix would be to put empty values by default, it should be fast enough and not have any major performance drawback
Mmmh, I'll think about it.
Anyways, thanks for the report!

**Comment by ItsTheSky** [comment]
Okay thanks you !
