### ISSUE TITLE
Support for 1.16.5

### ISSUE THREAD

**Issue by ItsTheSky** [upperlevel/book-api#17]
Hello!
I'm trying my plugin on different version, and got bad error on paper 1.16.5:
https://paste.md-5.net/ilubotucij.sql
Can you try adding support for 1.16.5 ? I think it's the cause since the exception is `UnsupportedVersionException`
Thanks ^^

**Comment by SnowyCoder** [comment]
This does not seem like a normal error, at least I've never seen an `java.lang.IllegalStateException: zip file closed` while working with it, were you moving/copying jars while this exception occurred? Anyways, I'll try to reproduce this

**Comment by SnowyCoder** [comment]
Yep, I can confirm on `Paper version git-Paper-488 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)` (the latest one i found), seems like it had problems while loading a class, most likely the jar file was removed before the JVM was able to read it.

**Comment by ItsTheSky** [comment]
Okay thanks you!
I'll try to find if nothings moved the jar file, but idk why it's only appear on 1.16.5 ^^'

**Comment by SnowyCoder** [comment]
Hello, did you find the cause?

**Comment by ItsTheSky** [comment]
Hi, I'm sorry, maybe a waste of time for you, very sorry about that ^^"
I figured out I changed my plugins file while the server were running, so 2 instance of my plugins (and also of your API) were runing at the same moment.
I'm rpetty it's the cause since i never get this error back from now ^^"
thanks again for help and sorry for waste of time 😓

**Comment by SnowyCoder** [comment]
Don't worry! It's always better to report a false bug than to miss a real one.
