### ISSUE TITLE
Version 1.4.1

### ISSUE THREAD

**Issue by iGabyTM** [upperlevel/book-api#19]
Version 1.4.1 is not available on maven central, but 1.4.2 is.
![https://repo.maven.apache.org/maven2/xyz/upperlevel/spigot/book/spigot-book-api/](https://i.imgur.com/GKTSTVY.png)

**Comment by SnowyCoder** [comment]
Strange, I am sure it was uploaded.
Well I've redeployed it, it should be up now, thanks for the issue!
