### ISSUE TITLE
Arguments with the book

### ISSUE THREAD

**Issue by thefrogline** [upperlevel/book-api#21]
Hello !, Currently with the example code that you put in the guide, I am trying to fill in certain fields of a book with the arguments of a command, is there any option of the plugin that does this ?, or how can I do it? this? (More than anything it is a question, sorry if it is something very basic)

**Comment by SnowyCoder** [comment]
You could put all of the arguments together and append it on a line of the book, only problem is you should also worry about wrapping if the arguments get too long

**Comment by thefrogline** [comment]
Yes !, I already managed to get the book to obtain the command arguments, thank you very much, but one last question to close this Issues, how can I open a book from another book? with click

**Comment by SnowyCoder** [comment]
You can add a command action so that the player will execute a command when he clicks it like so:
```java
pageBuilder.add(
    BookUtil.TextBuilder.of("click here")
            .color(ChatColor.AQUA)
            .style(ChatColor.BOLD)
            .onClick(BookUtil.ClickAction.runCommand("/yourcommand"))
            .onHover(BookUtil.HoverAction.showText("Change the book"))
            .build()
);
```
Then you listen for `/yuourcommand` (or another command you specify) and open another book.
A simpler option would be to create multiple pages and use `BookUtil.ClickAction.changePage(pageNumber)` to change it, it's a bit less flexible but it's much simpler.

**Comment by thefrogline** [comment]
Thank you very much for the serious attention, very good api and very good service, in a while I will leave my review with 5 stars on the plugin page ^^, and sorry for my bad english xd

**Comment by SnowyCoder** [comment]
Thanks, good luck with your plugin!
