### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by Level3301** [upperlevel/book-api#22]
spigot 1.8

compiles fine but when i try to create a book, it shows this error:
java.lang.ClassNotFoundException: xyz.upperlevel.spigot.book.BookUtil

**Comment by SnowyCoder** [comment]
Did you include the library JAR in your plugin?
If you want an example of what a final JAR should look like you can find it here: https://repo1.maven.org/maven2/xyz/upperlevel/spigot/book/spigot-book-api/1.4.2/spigot-book-api-1.4.2-example.jar (note that a real plugin JAR should also have the library relocated so it does not conflict with other library versions from other plugins)

**Comment by Level3301** [comment]
Hi, thanks for a reply.
I am using intellij idea.
Libraries:
![image](https://user-images.githubusercontent.com/58988922/116685214-444b7200-a9b2-11eb-84c8-8a2e0a3c818b.png)

**Comment by Level3301** [comment]
Should I include your library in jar?
![image](https://user-images.githubusercontent.com/58988922/116685341-76f56a80-a9b2-11eb-9009-99d285e377e5.png)
move it to the left side?

**Comment by SnowyCoder** [comment]
You should not include spigot in your plugin, and yep, you should include the BookApi extracted jar inside of it.

**Comment by Level3301** [comment]
Jar looks like this:
![image](https://user-images.githubusercontent.com/58988922/116685915-5e398480-a9b3-11eb-9644-159c4bbf0389.png)
But still getting this error:
Caused by: java.lang.NoClassDefFoundError: xyz/upperlevel/spigot/book/BookUtil

**Comment by Level3301** [comment]
I dont know how to put it in my plugin. It puts in Jar :(.

**Comment by SnowyCoder** [comment]
You should click on the + > "library files" then choose BookApi I think

**Comment by Level3301** [comment]
Yeah, thanks I missed "extract to jar". Thanks for help!
It doesnt show the error.

Another question.
Should this open the book?
`BookUtil.openPlayer(e.player, BookUtil.writtenBook()
                .author("Level3301")
                .title("Test book")
                .build()
        )`
(I use kotlin)

**Comment by Level3301** [comment]
Because it does not.

**Comment by SnowyCoder** [comment]
No problem! For the second question you should at least include a page in it, I think that minecraft will ignore it if there are none.

**Comment by Level3301** [comment]
Ok, I tried your example..
But another error... :(
![image](https://user-images.githubusercontent.com/58988922/116690196-567cde80-a9b9-11eb-8527-d36900284750.png)
It is an error in a library.

**Comment by Level3301** [comment]
`@EventHandler
    fun join(e:PlayerJoinEvent){
//        Bukkit.getScheduler().scheduleSyncDelayedTask(kernel.getPlugin(), {
//            addVoteItem(e.player)
//        }, 10L) // half a second

        val book = BookUtil.writtenBook()
                .author("SnowyCoder")
                .title("The Test-ament")
                .pages(arrayOf<BaseComponent>(
                        TextComponent("Introduction page")
                ),
                        PageBuilder()
                                .add(TextComponent("visit "))
                                .add(
                                        BookUtil.TextBuilder.of("Spigot")
                                                .color(ChatColor.GOLD)
                                                .style(ChatColor.BOLD, ChatColor.ITALIC)
                                                .onClick(BookUtil.ClickAction.openUrl("https://www.spigotmc.org"))
                                                .onHover(BookUtil.HoverAction.showText("Open spigot!"))
                                                .build()
                                )
                                .add(" or ")
                                .add(
                                        *ComponentBuilder("Bukkit")
                                                .color(net.md_5.bungee.api.ChatColor.BLUE)
                                                .bold(true)
                                                .italic(true)
                                                .event(ClickEvent(ClickEvent.Action.OPEN_URL, "https://bukkit.org"))
                                                .event(HoverEvent(HoverEvent.Action.SHOW_TEXT, arrayOf<BaseComponent>(TextComponent("Open bukkit!"))))
                                                .create()
                                )
                                .newLine()
                                .add("I think that the ")
                                .add(
                                        BookUtil.TextBuilder.of("TextBuilder")
                                                .color(ChatColor.AQUA)
                                                .style(ChatColor.BOLD)
                                                **.onClick(BookUtil.ClickAction.changePage(3))** // this is causing it
                                                .onHover(BookUtil.HoverAction.showText("TextBuilder's page"))
                                                .build()
                                )
                                .add(" is really useful to ")
                                .add(
                                        BookUtil.TextBuilder.of("you")
                                                .color(ChatColor.AQUA)
                                                .style(ChatColor.BOLD)
                                                .onClick(BookUtil.ClickAction.runCommand("/kill")) //lol
                                                .onHover(BookUtil.HoverAction.showText("Kill yasself"))
                                                .build()
                                )
                                .build(),
                        PageBuilder()
                                .add("TextBuilder's page")
                                .newLine().newLine()
                                .add("Isn't this amazing?")
                                .build()
                )
                .build()

        BookUtil.openPlayer(e.player, book)
    }`

**Comment by SnowyCoder** [comment]
I saw the same error on other 1.8 users but I have no idea what's causing it since they solved it without reporting how.
Can you give me your spigot version? (and are you using the latest?)

**Comment by Level3301** [comment]
Ok, so I am using this:
![image](https://user-images.githubusercontent.com/58988922/116690559-d73bda80-a9b9-11eb-9ed7-cb7e49bfe927.png)

**Comment by Level3301** [comment]
I will download the latest for sure.

**Comment by Level3301** [comment]
Error stays even after I have installed the latest 1.8 spigot. :(

**Comment by Level3301** [comment]
So I commented that line, now no error and no book. :(

**Comment by SnowyCoder** [comment]
So, I tried using the 1.8 version from getbukkit and you're right, CHANGE_PAGE is not implemented yet (please use 1.8.8).
However commenting all of the changePage lines seems to work fine.

**Comment by SnowyCoder** [comment]
Yep, after some testing I found out that spigot does not really like opening books right when a player joins. Try adding a slight delay to it:
```java
Bukkit.getScheduler().runTaskLater(this, () -> {
    ItemStack book = /*create your book*/;
    BookUtil.openPlayer(e.getPlayer(), book);
}, 1);
```
I have no idea why, but this seems to work fine

**Comment by Level3301** [comment]
Ok, I will try.

**Comment by Level3301** [comment]
![image](https://user-images.githubusercontent.com/58988922/116693871-c346a780-a9be-11eb-90f5-11dbb32c3130.png)
Thanks it is now working!
Thanks for your help! 👍
