### ISSUE TITLE
Doesnt work on 1.17

### ISSUE THREAD

**Issue by alekso56** [upperlevel/book-api#24]

**Comment by elgbar** [comment]
It seems `net.minecraft.server` packages now do no include the revision nor the version. E.g. pre 1.17 `EntityPlayer` would be `net.minecraft.server.v1_16_R3.EntityPlayer`, while post 1.17 it is `net.minecraft.server.level.EntityPlayer`. 

The solution is simply to map all NMS classes to the new structure to allow this to work again.
