### ISSUE TITLE
Question :)

### ISSUE THREAD

**Issue by J-Laforge** [upperlevel/book-api#26]
Hi,
I don't know where to post my question so I will just put it there. 
Is there a way to update the content of a page on click event without have to close and re-open a book ?
Thanks.

**Comment by SnowyCoder** [comment]
Mmmh, that's actually a good question, I'm not really sure.
The books are not server-side, when the player opens a book bukkit sends the whole book to the client and that's basically it.
You can send a command when an user clicks so you could intercept it, close and reopen the book automatically, but I don't think you can force the client on a particular page, so you should do a single-page book.
Now that I think about it I'm not even sure if it works or if would be noticeable

**Comment by J-Laforge** [comment]
Ok thanks for your response. 👍
