### ISSUE TITLE
Split across pages if max lines exceeded

### ISSUE THREAD

**Issue by PikaMug** [upperlevel/book-api#30]
It would be nice if we could optionally set a maximum number of lines (`#add`s) per PageBuilder that, if exceeded, would automatically push extra lines to subsequent pages.

**Comment by SnowyCoder** [comment]
It would be nice but it would require some kind of simulation to know when to split lines (and also some edge cases that don't seem obvious).
It seems quite complex and I have very little time to work on this, but I'll accept pull requests if anyone wants to help.

**Comment by PikaMug** [comment]
I see what you mean. Even if we just split on "\n" and count the lines, there's no way to tell where valid pages should start/end for a particular use case. Best to let users handle this on their own, then.
