### ISSUE TITLE
pls update to 1.20.4

### ISSUE THREAD

**Issue by FortuneMidnight** [upperlevel/book-api#33]
pls update to 1.20.4

**Comment by SnowyCoder** [comment]
Hello, this library does not use any NMS code anymore so it should be compatible with spigot 1.20.4, what error did you encounter?

**Comment by SnowyCoder** [comment]
(sorry, I missclicked)

**Comment by FortuneMidnight** [comment]
Strangely enough it works now, sorry

I must have made a mistake xd
