### ISSUE TITLE
Not works on 1.12.2?

### ISSUE THREAD

**Issue by caoli5288** [upperlevel/book-api#4]
No any effect while call BookUtil.openBook()

**Comment by SnowyCoder** [comment]
Just tested the latest book-api example with `CraftBukkit version git-Spigot-109b080-a3decfd (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)` and everything seems tto work finely, could you make a more in-depth explanation of the error (maybe with code samples)?

**Comment by caoli5288** [comment]
It works well with written book but not with writable one.

Is it any way force player open an writable book in server side?

**Comment by SnowyCoder** [comment]
I don't think that it's possible.
The protocol doesn't seem to support that: 
https://bukkit.org/threads/force-player-to-open-book-quill.417573/

**Comment by caoli5288** [comment]
THX

**Comment by SnowyCoder** [comment]
If you listen to the packet stream (with ProtocolLib or similar) you can see that when the client opens a normal book the server sends a `PacketPlayOutCustomPayload` telling the client to open the book (the data inside should be "MC|OPEN" if I remember correctly).
That doesn't happen with book and quill, the client opens it without the need for a server packet (altough you could listen when the client opens one by listening the `PacketPlayInBlockPlace` packet)
